import type { SportType } from './types';

export interface SportPresentation {
  label: string;
  headline: string;
  format: string;
  rhythm: string;
  atmosphere: string;
  emptyState: string;
  statusVerb: string;
  scoreLabel: string;
  accentText: string;
  accentRing: string;
  accentPanel: string;
  accentBadge: string;
  heroGradient: string;
  fieldShell: string;
  eventGlow: string;
  keyMoments: string[];
}

export const SPORT_PRESENTATION: Record<SportType, SportPresentation> = {
  soccer: {
    label: 'Soccer',
    headline: 'Shape, space, and momentum swings over 90 minutes.',
    format: '11 v 11 · 2 x 45 min',
    rhythm: 'territory battles, transitions, late pressure',
    atmosphere: 'full-pitch control, pressing, and crowd tension',
    emptyState: 'Set the lineups and wait for the opening whistle.',
    statusVerb: 'Kickoff ready',
    scoreLabel: 'Goals',
    accentText: 'text-emerald-300',
    accentRing: 'ring-emerald-500/30',
    accentPanel: 'from-emerald-500/20 via-emerald-400/8 to-transparent',
    accentBadge: 'bg-emerald-500/15 text-emerald-200 border-emerald-400/20',
    heroGradient: 'from-emerald-500/20 via-emerald-400/10 to-slate-950',
    fieldShell: 'from-emerald-500/12 via-transparent to-slate-950',
    eventGlow: 'shadow-[0_0_0_1px_rgba(16,185,129,0.15)]',
    keyMoments: ['Pressing traps', 'Final-third entries', 'Late substitutions'],
  },
  basketball: {
    label: 'Basketball',
    headline: 'Fast possessions, shot volume, and spacing decisions.',
    format: '5 v 5 · 4 x 12 min',
    rhythm: 'pace control, shot quality, and runs',
    atmosphere: 'tempo spikes, scoring bursts, and half-court adjustments',
    emptyState: 'Pick your matchup and get ready for the opening tip.',
    statusVerb: 'Tipoff ready',
    scoreLabel: 'Points',
    accentText: 'text-amber-300',
    accentRing: 'ring-amber-500/30',
    accentPanel: 'from-amber-500/20 via-orange-400/10 to-transparent',
    accentBadge: 'bg-amber-500/15 text-amber-100 border-amber-300/20',
    heroGradient: 'from-amber-500/20 via-orange-400/10 to-slate-950',
    fieldShell: 'from-amber-500/12 via-transparent to-slate-950',
    eventGlow: 'shadow-[0_0_0_1px_rgba(245,158,11,0.15)]',
    keyMoments: ['Paint pressure', 'Three-point volume', 'Bench rotations'],
  },
  baseball: {
    label: 'Baseball',
    headline: 'Pitch-by-pitch leverage and situational pressure.',
    format: '9 v 9 · 9 innings',
    rhythm: 'counts, sequencing, and run manufacturing',
    atmosphere: 'infield tension, bullpen choices, and clutch at-bats',
    emptyState: 'Choose a stadium and wait for the first pitch.',
    statusVerb: 'First pitch ready',
    scoreLabel: 'Runs',
    accentText: 'text-lime-300',
    accentRing: 'ring-lime-500/30',
    accentPanel: 'from-lime-500/20 via-green-400/10 to-transparent',
    accentBadge: 'bg-lime-500/15 text-lime-100 border-lime-300/20',
    heroGradient: 'from-lime-500/20 via-green-400/10 to-slate-950',
    fieldShell: 'from-lime-500/12 via-transparent to-slate-950',
    eventGlow: 'shadow-[0_0_0_1px_rgba(132,204,22,0.15)]',
    keyMoments: ['Pitch counts', 'Basepath threats', 'Late innings'],
  },
  football: {
    label: 'Football',
    headline: 'Field position, play calling, and explosive downs.',
    format: '11 v 11 · 4 x 15 min',
    rhythm: 'drive construction, third-down calls, red-zone execution',
    atmosphere: 'clock management, collisions, and situational tactics',
    emptyState: 'Build the matchup and wait for the kickoff.',
    statusVerb: 'Kickoff ready',
    scoreLabel: 'Points',
    accentText: 'text-red-300',
    accentRing: 'ring-red-500/30',
    accentPanel: 'from-red-500/20 via-rose-400/10 to-transparent',
    accentBadge: 'bg-red-500/15 text-red-100 border-red-300/20',
    heroGradient: 'from-red-500/20 via-rose-400/10 to-slate-950',
    fieldShell: 'from-red-500/12 via-transparent to-slate-950',
    eventGlow: 'shadow-[0_0_0_1px_rgba(239,68,68,0.15)]',
    keyMoments: ['Third down', 'Blitz timing', 'Red-zone calls'],
  },
  hockey: {
    label: 'Hockey',
    headline: 'Shift changes, puck pressure, and special teams swings.',
    format: '6 v 6 · 3 x 20 min',
    rhythm: 'zone entries, forecheck pressure, and man advantages',
    atmosphere: 'ice tilt, quick counters, and line chemistry',
    emptyState: 'Select the rink and get set for puck drop.',
    statusVerb: 'Puck drop ready',
    scoreLabel: 'Goals',
    accentText: 'text-cyan-300',
    accentRing: 'ring-cyan-500/30',
    accentPanel: 'from-cyan-500/20 via-sky-400/10 to-transparent',
    accentBadge: 'bg-cyan-500/15 text-cyan-100 border-cyan-300/20',
    heroGradient: 'from-cyan-500/20 via-sky-400/10 to-slate-950',
    fieldShell: 'from-cyan-500/12 via-transparent to-slate-950',
    eventGlow: 'shadow-[0_0_0_1px_rgba(6,182,212,0.15)]',
    keyMoments: ['Power plays', 'High-danger chances', 'Line changes'],
  },
  tennis: {
    label: 'Tennis',
    headline: 'Serve patterns, rally control, and pressure points.',
    format: 'Singles · best of 3 sets',
    rhythm: 'serve plus one, return depth, and break-point tension',
    atmosphere: 'quiet pressure, quick momentum flips, and clutch serving',
    emptyState: 'Load the matchup and wait for the first serve.',
    statusVerb: 'First serve ready',
    scoreLabel: 'Sets',
    accentText: 'text-blue-200',
    accentRing: 'ring-blue-500/30',
    accentPanel: 'from-blue-500/20 via-indigo-400/10 to-transparent',
    accentBadge: 'bg-blue-500/15 text-blue-100 border-blue-300/20',
    heroGradient: 'from-blue-500/20 via-indigo-400/10 to-slate-950',
    fieldShell: 'from-blue-500/12 via-transparent to-slate-950',
    eventGlow: 'shadow-[0_0_0_1px_rgba(59,130,246,0.15)]',
    keyMoments: ['Break points', 'Second serves', 'Net approaches'],
  },
  golf: {
    label: 'Golf',
    headline: 'Risk management, precision, and hole-by-hole variance.',
    format: 'Stroke play · 18 holes',
    rhythm: 'tee-shot placement, approach control, and putting pace',
    atmosphere: 'quiet pressure and tiny margins over a long round',
    emptyState: 'Set the round and wait for the opening tee shot.',
    statusVerb: 'Tee shot ready',
    scoreLabel: 'Strokes',
    accentText: 'text-green-200',
    accentRing: 'ring-green-500/30',
    accentPanel: 'from-green-500/20 via-emerald-400/10 to-transparent',
    accentBadge: 'bg-green-500/15 text-green-100 border-green-300/20',
    heroGradient: 'from-green-500/20 via-emerald-400/10 to-slate-950',
    fieldShell: 'from-green-500/12 via-transparent to-slate-950',
    eventGlow: 'shadow-[0_0_0_1px_rgba(34,197,94,0.15)]',
    keyMoments: ['Tee dispersion', 'Green approach', 'Recovery shots'],
  },
  cricket: {
    label: 'Cricket',
    headline: 'Strike rotation, wicket pressure, and over management.',
    format: 'T20 · 20 overs',
    rhythm: 'powerplay aggression, middle-over control, death-over execution',
    atmosphere: 'field settings, bowling variety, and chase pressure',
    emptyState: 'Set the sides and wait for the first delivery.',
    statusVerb: 'First ball ready',
    scoreLabel: 'Runs',
    accentText: 'text-yellow-200',
    accentRing: 'ring-yellow-500/30',
    accentPanel: 'from-yellow-500/20 via-amber-400/10 to-transparent',
    accentBadge: 'bg-yellow-500/15 text-yellow-100 border-yellow-300/20',
    heroGradient: 'from-yellow-500/20 via-amber-400/10 to-slate-950',
    fieldShell: 'from-yellow-500/12 via-transparent to-slate-950',
    eventGlow: 'shadow-[0_0_0_1px_rgba(234,179,8,0.15)]',
    keyMoments: ['Powerplay overs', 'Wicket bursts', 'Death bowling'],
  },
  boxing: {
    label: 'Boxing',
    headline: 'Distance control, combinations, and attritional damage.',
    format: '1 v 1 · 12 rounds',
    rhythm: 'jab control, counters, and late-round bursts',
    atmosphere: 'measured pressure with sudden fight-ending swings',
    emptyState: 'Choose the fight and wait for the opening bell.',
    statusVerb: 'Opening bell ready',
    scoreLabel: 'Rounds',
    accentText: 'text-rose-200',
    accentRing: 'ring-rose-500/30',
    accentPanel: 'from-rose-500/20 via-red-400/10 to-transparent',
    accentBadge: 'bg-rose-500/15 text-rose-100 border-rose-300/20',
    heroGradient: 'from-rose-500/20 via-red-400/10 to-slate-950',
    fieldShell: 'from-rose-500/12 via-transparent to-slate-950',
    eventGlow: 'shadow-[0_0_0_1px_rgba(244,63,94,0.15)]',
    keyMoments: ['Counter windows', 'Body work', 'Knockdown threats'],
  },
  mma: {
    label: 'MMA',
    headline: 'Range shifts, takedown threats, and scramble volatility.',
    format: '1 v 1 · 3 rounds',
    rhythm: 'striking setups, clinch entries, and ground transitions',
    atmosphere: 'open-ended pressure with rapid tactical pivots',
    emptyState: 'Lock in the matchup and wait for the first exchange.',
    statusVerb: 'Fight ready',
    scoreLabel: 'Rounds',
    accentText: 'text-slate-200',
    accentRing: 'ring-slate-400/30',
    accentPanel: 'from-slate-500/20 via-zinc-400/10 to-transparent',
    accentBadge: 'bg-slate-500/15 text-slate-100 border-slate-300/20',
    heroGradient: 'from-slate-500/20 via-zinc-400/10 to-slate-950',
    fieldShell: 'from-slate-500/12 via-transparent to-slate-950',
    eventGlow: 'shadow-[0_0_0_1px_rgba(148,163,184,0.15)]',
    keyMoments: ['Takedown chains', 'Clinch control', 'Submission threats'],
  },
  racing: {
    label: 'Racing',
    headline: 'Pace management, overtakes, and pit-lane timing.',
    format: 'Head-to-head · 50 laps',
    rhythm: 'clean exits, tire preservation, and attack windows',
    atmosphere: 'constant micro-gains with sudden strategic swings',
    emptyState: 'Configure the grid and wait for lights out.',
    statusVerb: 'Lights out ready',
    scoreLabel: 'Race position',
    accentText: 'text-neutral-100',
    accentRing: 'ring-neutral-400/30',
    accentPanel: 'from-neutral-500/20 via-zinc-400/10 to-transparent',
    accentBadge: 'bg-neutral-500/15 text-neutral-100 border-neutral-300/20',
    heroGradient: 'from-neutral-500/20 via-zinc-400/10 to-slate-950',
    fieldShell: 'from-neutral-500/12 via-transparent to-slate-950',
    eventGlow: 'shadow-[0_0_0_1px_rgba(161,161,170,0.15)]',
    keyMoments: ['Pit windows', 'Tire wear', 'Final-lap attacks'],
  },
};

export function getSportPresentation(sport: SportType): SportPresentation {
  return SPORT_PRESENTATION[sport];
}